config/routes.rb
Rails.application.routes.draw do
  resources :calenders

  devise_for :users
  resources :users, :only => [:index, :show]
  root 'date#index'
  get '/result' => "date#result"
  get '/users/:id/mypage' => "users#mypage"

end

app/models/calender.rb
class Calender < ActiveRecord::Base
  self.primary_key = :user_id 
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :calenders
  self.primary_key = :id 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :nickname, :gender, :email, :password, :password_confirmation, :date_1, :date_2, :date_1_time, :date_2_time, :avatar
      end
    end
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: [:show, :edit, :update, :destroy]

  # GET /calenders
  # GET /calenders.json
  def index
    @calenders = Calender.all
  end

  # GET /calenders/1
  # GET /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders
  # POST /calenders.json
  def create
    @calender = Calender.new(calender_params)
    @calender.user_id = current_user.id

    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: 'Calender was successfully created.' }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1
  # PATCH/PUT /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: 'Calender was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1
  # DELETE /calenders/1.json
  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Calender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_params
      params.require(:calender).permit(:date_1, :date_2, :user_id)
    end
end

app/controllers/date_controller.rb
class DateController < ApplicationController
  
  def index
    @users = User.all
    @currentUser = current_user.id
  end

  def result
    @currentUser = current_user.id
    array = []
    params_1 = params[:first]['born_on']
    params_2 = params[:second]['born']
    array << params_1
    array << params_2
    @dates = User.joins("LEFT JOIN calenders ON calenders.user_id = users.id")
            .where("users.date_1 IN (?) OR users.date_2 IN (?)", array, array).where("users.gender" => params[:gender] )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def show
    @user = User.find(params[:id])
   end

   def mypage
    @currentUser = current_user
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/date_helper.rb
module DateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calenders/_form.html.erb
<%= form_for(@calender) do |f| %>
  <% if @calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% @calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_1 %><br>
    <%= f.text_field :date_1 %>
  </div>
  <div class="field">
    <%= f.label :date_2 %><br>
    <%= f.text_field :date_2 %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calenders/edit.html.erb
<h1>Editing Calender</h1>

<%= render 'form' %>

<%= link_to 'Show', @calender %> |
<%= link_to 'Back', calenders_path %>

app/views/calenders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calenders</h1>

<table>
  <thead>
    <tr>
      <th>Date 1</th>
      <th>Date 2</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calenders.each do |calender| %>
      <tr>
        <td><%= calender.date_1 %></td>
        <td><%= calender.date_2 %></td>
        <td><%= calender.user_id %></td>
        <td><%= link_to 'Show', calender %></td>
        <td><%= link_to 'Edit', edit_calender_path(calender) %></td>
        <td><%= link_to 'Destroy', calender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calender', new_calender_path %>

app/views/calenders/new.html.erb
<h1>New Calender</h1>

<%= render 'form' %>

<%= link_to 'Back', calenders_path %>

app/views/calenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date 1:</strong>
  <%= @calender.date_1 %>
</p>

<p>
  <strong>Date 2:</strong>
  <%= @calender.date_2 %>
</p>

<p>
  <strong>User:</strong>
  <%= @calender.user_id %>
</p>

<%= link_to 'Edit', edit_calender_path(@calender) %> |
<%= link_to 'Back', calenders_path %>

app/views/date/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <style>
  header {text-align: center;}

  </style>
  
  <body>
    <header>
    <h2>Rakutinder</h2>

      <%= form_tag("/result", :validate=> true, :method => :get ) do %>

<h5>第一希望日<%= date_field("first", "born_on", :id => 'date_1',
                                value: Time.now.strftime("%Y-%m-%d")) %>


　　第二希望日<%= date_field("second", "born", :id => 'date_2', 
                                value: Time.now.strftime("%Y-%m-%d")) %>


<%= select_tag 'gender', options_for_select({"男性" => "m", "女性" => "f"}),  :prompt => "性別" %>

<h4><button id="submit" onClick="return check()">検索する</button></h4>
<% end %>
</header>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/date/result.html.erb
<style>
body {margin: 0 auto;
}

body {
  text-align: center;
}
</style>

<link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">

 <header>
    <h2>Rakutinder</h2>

      <%= form_tag("/result", :validate=> true, :method => :get ) do %>

<h5>第一希望日<%= date_field("first", "born_on", :id => 'date_1',
                                value: Time.now.strftime("%Y-%m-%d")) %>


　　第二希望日<%= date_field("second", "born", :id => 'date_2', 
                                value: Time.now.strftime("%Y-%m-%d")) %>


　性別　<%= select_tag 'gender', options_for_select({"男性" => "m", "女性" => "f"}) %>


<h4><button id="submit" onClick="return check()">検索する</button></h4>
<% end %>
</header>

<% if @dates.present? %>
<% @dates.each do |date| %>
<div class="col-xs-12 col-md-4 col-lg-3">
<p></p>
<p><%= image_tag date.avatar.url(:medium) %></p>
<h4><a href ="/users/<%= date.id %>">ニックネーム : <%= date.nickname %></a></h4>
</div>
<% end %>
<% end %>

<% if @dates.empty? %>
<h3>一人もいませんでした</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rakutinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<style>
body {margin: 0 auto;
}

body {
  text-align: center;
}
</style>

<link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">

 <header>
    <h2>Rakutinder</h2>

      <%= form_tag("/result", :validate=> true, :method => :get ) do %>

<h5>第一希望日<%= date_field("first", "born_on", :id => 'date_1',
                                value: Time.now.strftime("%Y-%m-%d")) %>


　　第二希望日<%= date_field("second", "born", :id => 'date_2', 
                                value: Time.now.strftime("%Y-%m-%d")) %>


　性別　<%= select_tag 'gender', options_for_select({"男性" => "m", "女性" => "f"}) %>


<h4><button id="submit" onClick="return check()">検索する</button></h4>
<% end %>
</header>
<% if @dates.present? %>
<% @dates.each do |date| %>
<div class="col-xs-12 col-md-4 col-lg-3">
<p></p>
<p><%= image_tag date.avatar.url(:medium) %></p>
<h4><%= link_to 'ニックネーム :date.nickname', user_path %></h4>
</div>
<% end %>
<% end %>

<% if @dates.empty? %>
<h3>一人もいませんでした</h3>
<% end %>

app/views/users/mypage.html.erb
<h4><%= @currentUser.nickname %></h4>
<p><%= image_tag @currentUser.avatar.url(:medium) %></p>

app/views/users/show.html.erb
<link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">
<style>
  #date_time_1 {
    display: none;
  }

  #date_time_2 {
    display: none;
  }

</style>

<div class="col-xs-12 col-md-4 col-lg-3">
<p></p>
<p><%= image_tag @user.avatar.url(:medium) %></p>
<h4>ニックネーム : <%= @user.nickname %></h4>

<h4>日付
<select id="select" onchange="changeSelect()">
<option>日時を選択してください</option>
<option value="1"><%= Date.parse(@user.date_1).strftime("%Y年%m月%d日") %></option>
<option value="2"><%= Date.parse(@user.date_2).strftime("%Y年%m月%d日") %></option>
</select>
</h4>
<p id ="date_time_1"><input type="radio" name="example" value="サンプル">　<%= @user.date_1_time %></p>
<p id ="date_time_2"><input type="radio" name="example" value="サンプル">　<%= @user.date_2_time %></p>


<button type="button" class="btn btn-danger">デートを申し込む</button>
</div>


<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script>
function changeSelect(){
    var select = document.getElementById('select');
    var options =
        document.getElementById('select').options;
    var value = options.item(select.selectedIndex).value;

  if (value == 1){
    $('#date_time_1').show();
    $('#date_time_2').hide();
}else if (value == 2){
    $('#date_time_1').hide();
    $('#date_time_2').show();
  }
}
</script>

app/views/users/start.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <style>
  header {text-align: center;}

  </style>
  
  <body>
    <header>
    <h2>Rakutinder</h2>

      <%= form_tag("/result", :validate=> true, :method => :get ) do %>

<h5>第一希望日<%= date_field("first", "born_on", :id => 'date_1',
                                value: Time.now.strftime("%Y-%m-%d")) %>


　　第二希望日<%= date_field("second", "born", :id => 'date_2', 
                                value: Time.now.strftime("%Y-%m-%d")) %>


<%= select_tag 'gender', options_for_select({"男性" => "m", "女性" => "f"}),  :prompt => "性別" %>

<h4><button id="submit" onClick="return check()">検索する</button></h4>
<% end %>
</header>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>